export const toeicParts = [
  {
    id: 1,
    name: "Photographs",
    nameTH: "ภาพถ่าย",
    questions: 6,
    icon: "📷",
    description: "Describe photographs accurately",
    descriptionTH: "บรรยายภาพถ่ายอย่างถูกต้อง",
    tips: [
      "Focus on the main action or subject",
      "Listen for what IS happening, not what might happen",
      "Eliminate clearly wrong answers first",
    ],
    tipsTH: [
      "สังเกตกิจกรรมหรือวัตถุหลัก",
      "ฟังสิ่งที่กำลังเกิดขึ้น ไม่ใช่สิ่งที่อาจเกิดขึ้น",
      "ตัดตัวเลือกที่ผิดชัดเจนออกก่อน",
    ],
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 2,
    name: "Question-Response",
    nameTH: "คำถาม-คำตอบ",
    questions: 25,
    icon: "💬",
    description: "Choose the best response to questions",
    descriptionTH: "เลือกคำตอบที่ดีที่สุด",
    tips: [
      "Listen for question words (who, what, when, where, why, how)",
      "Watch out for indirect answers",
      "Eliminate echo responses",
    ],
    tipsTH: [
      "ฟัง question words (who, what, when, where, why, how)",
      "ระวังคำตอบที่ตอบทางอ้อม",
      "ตัดคำตอบที่ซ้ำคำในคำถามออก",
    ],
    color: "from-purple-500 to-pink-500",
  },
  {
    id: 3,
    name: "Conversations",
    nameTH: "บทสนทนา",
    questions: 39,
    icon: "🗣️",
    description: "Understand short conversations",
    descriptionTH: "ทำความเข้าใจบทสนทนาสั้น",
    tips: [
      "Read questions before listening",
      "Note the relationship between speakers",
      "Watch for graphic-integrated questions",
    ],
    tipsTH: [
      "อ่านคำถามก่อนฟัง",
      "สังเกตความสัมพันธ์ระหว่างผู้พูด",
      "ระวังคำถามที่ใช้ภาพหรือตาราง",
    ],
    color: "from-green-500 to-teal-500",
  },
  {
    id: 4,
    name: "Talks",
    nameTH: "บรรยาย",
    questions: 30,
    icon: "🎙️",
    description: "Understand monologues and announcements",
    descriptionTH: "ทำความเข้าใจการพูดคนเดียวและประกาศ",
    tips: [
      "Anticipate the topic from the introduction",
      "Focus on key numbers, names, and dates",
      "Listen for purpose and main idea",
    ],
    tipsTH: [
      "คาดเดาหัวข้อจากประโยคแรก",
      "จดจำตัวเลข ชื่อ และวันที่สำคัญ",
      "ฟังวัตถุประสงค์และใจความสำคัญ",
    ],
    color: "from-orange-500 to-red-500",
  },
  {
    id: 5,
    name: "Incomplete Sentences",
    nameTH: "เติมประโยค",
    questions: 30,
    icon: "✏️",
    description: "Complete sentences with correct grammar",
    descriptionTH: "เติมประโยคด้วยไวยากรณ์ที่ถูกต้อง",
    tips: [
      "Identify the part of speech needed",
      "Check subject-verb agreement",
      "Look for time/context clues for tenses",
    ],
    tipsTH: [
      "ระบุ part of speech ที่ต้องการ",
      "ตรวจสอบ subject-verb agreement",
      "หา clues บอก tense จาก context",
    ],
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: 6,
    name: "Text Completion",
    nameTH: "เติมบทความ",
    questions: 16,
    icon: "📝",
    description: "Complete texts with appropriate words",
    descriptionTH: "เติมคำลงในบทความ",
    tips: [
      "Read the whole text for context first",
      "Check discourse markers and connectors",
      "Ensure logical flow between sentences",
    ],
    tipsTH: [
      "อ่านบทความทั้งหมดเพื่อเข้าใจ context ก่อน",
      "ตรวจสอบ discourse markers และ connectors",
      "ตรวจสอบความสอดคล้องระหว่างประโยค",
    ],
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: 7,
    name: "Reading Comprehension",
    nameTH: "การอ่านเพื่อความเข้าใจ",
    questions: 54,
    icon: "📖",
    description: "Read and answer questions about passages",
    descriptionTH: "อ่านและตอบคำถามจากบทความ",
    tips: [
      "Scan for keywords from questions",
      "Read topic sentences of each paragraph",
      "Watch for NOT/EXCEPT questions",
    ],
    tipsTH: [
      "Scan หา keywords จากคำถาม",
      "อ่านประโยคแรกของแต่ละย่อหน้า",
      "ระวังคำถาม NOT/EXCEPT",
    ],
    color: "from-rose-500 to-pink-500",
  },
];

export const vocabularyCategories = [
  {
    id: "business",
    name: "Business",
    nameTH: "ธุรกิจ",
    icon: "💼",
    count: 200,
    color: "bg-blue-100 text-blue-700 border-blue-200",
  },
  {
    id: "office",
    name: "Office",
    nameTH: "สำนักงาน",
    icon: "🏢",
    count: 150,
    color: "bg-purple-100 text-purple-700 border-purple-200",
  },
  {
    id: "finance",
    name: "Finance",
    nameTH: "การเงิน",
    icon: "💰",
    count: 180,
    color: "bg-green-100 text-green-700 border-green-200",
  },
  {
    id: "travel",
    name: "Travel",
    nameTH: "การเดินทาง",
    icon: "✈️",
    count: 120,
    color: "bg-orange-100 text-orange-700 border-orange-200",
  },
  {
    id: "technology",
    name: "Technology",
    nameTH: "เทคโนโลยี",
    icon: "💻",
    count: 160,
    color: "bg-cyan-100 text-cyan-700 border-cyan-200",
  },
  {
    id: "health",
    name: "Health",
    nameTH: "สุขภาพ",
    icon: "🏥",
    count: 100,
    color: "bg-red-100 text-red-700 border-red-200",
  },
];

export const vocabularyWords = [
  {
    id: 1,
    word: "negotiate",
    pronunciation: "/nɪˈɡoʊʃieɪt/",
    partOfSpeech: "verb",
    meaning: "To discuss something to reach an agreement",
    meaningTH: "เจรจาต่อรอง",
    example: "We need to negotiate the terms of the contract.",
    exampleTH: "เราต้องเจรจาเงื่อนไขของสัญญา",
    category: "business",
    level: "intermediate",
    synonyms: ["bargain", "discuss", "mediate"],
  },
  {
    id: 2,
    word: "implement",
    pronunciation: "/ˈɪmplɪment/",
    partOfSpeech: "verb",
    meaning: "To put a plan into action",
    meaningTH: "นำไปปฏิบัติ / ดำเนินการ",
    example: "The company will implement the new policy next month.",
    exampleTH: "บริษัทจะนำนโยบายใหม่ไปปฏิบัติเดือนหน้า",
    category: "business",
    level: "intermediate",
    synonyms: ["execute", "apply", "carry out"],
  },
  {
    id: 3,
    word: "allocate",
    pronunciation: "/ˈæləkeɪt/",
    partOfSpeech: "verb",
    meaning: "To distribute resources for a particular purpose",
    meaningTH: "จัดสรร / แบ่งปัน",
    example: "The budget was allocated to three departments.",
    exampleTH: "งบประมาณถูกจัดสรรให้สามแผนก",
    category: "finance",
    level: "advanced",
    synonyms: ["assign", "distribute", "apportion"],
  },
  {
    id: 4,
    word: "itinerary",
    pronunciation: "/aɪˈtɪnəreri/",
    partOfSpeech: "noun",
    meaning: "A planned route or journey",
    meaningTH: "แผนการเดินทาง / กำหนดการ",
    example: "Please send me the travel itinerary for next week.",
    exampleTH: "กรุณาส่งแผนการเดินทางสัปดาห์หน้าให้ฉัน",
    category: "travel",
    level: "intermediate",
    synonyms: ["schedule", "agenda", "plan"],
  },
  {
    id: 5,
    word: "quarterly",
    pronunciation: "/ˈkwɔːrtərli/",
    partOfSpeech: "adjective/adverb",
    meaning: "Happening four times a year",
    meaningTH: "รายไตรมาส / ทุกสามเดือน",
    example: "We review our targets on a quarterly basis.",
    exampleTH: "เราทบทวนเป้าหมายทุกไตรมาส",
    category: "finance",
    level: "intermediate",
    synonyms: ["periodic", "regular"],
  },
  {
    id: 6,
    word: "procurement",
    pronunciation: "/prəˈkjʊərmənt/",
    partOfSpeech: "noun",
    meaning: "The process of obtaining goods or services",
    meaningTH: "การจัดซื้อจัดจ้าง",
    example: "The procurement department handles all supplier contracts.",
    exampleTH: "ฝ่ายจัดซื้อดูแลสัญญาของผู้จัดหาสินค้าทั้งหมด",
    category: "business",
    level: "advanced",
    synonyms: ["acquisition", "purchasing", "sourcing"],
  },
  {
    id: 7,
    word: "invoice",
    pronunciation: "/ˈɪnvɔɪs/",
    partOfSpeech: "noun",
    meaning: "A list of goods/services with their prices",
    meaningTH: "ใบแจ้งหนี้ / ใบกำกับสินค้า",
    example: "Please send an invoice for the services provided.",
    exampleTH: "กรุณาส่งใบแจ้งหนี้สำหรับบริการที่ให้",
    category: "finance",
    level: "beginner",
    synonyms: ["bill", "statement", "receipt"],
  },
  {
    id: 8,
    word: "efficient",
    pronunciation: "/ɪˈfɪʃənt/",
    partOfSpeech: "adjective",
    meaning: "Working in a well-organized and productive way",
    meaningTH: "มีประสิทธิภาพ",
    example: "The new system is much more efficient than before.",
    exampleTH: "ระบบใหม่มีประสิทธิภาพมากกว่าเดิม",
    category: "office",
    level: "beginner",
    synonyms: ["productive", "effective", "capable"],
  },
];

export const grammarTopics = [
  {
    id: "tenses",
    name: "Verb Tenses",
    nameTH: "กาลกริยา",
    icon: "⏰",
    subtopics: 12,
    importance: "very high",
    color: "from-blue-500 to-indigo-600",
    description: "Present, Past, Future and Perfect tenses",
    descriptionTH: "Present, Past, Future และ Perfect tenses",
  },
  {
    id: "conditionals",
    name: "Conditionals",
    nameTH: "ประโยคเงื่อนไข",
    icon: "🔀",
    subtopics: 4,
    importance: "high",
    color: "from-purple-500 to-pink-600",
    description: "If-clauses and conditional structures",
    descriptionTH: "If-clauses และโครงสร้างเงื่อนไข",
  },
  {
    id: "passive",
    name: "Passive Voice",
    nameTH: "Passive Voice",
    icon: "🔄",
    subtopics: 6,
    importance: "very high",
    color: "from-green-500 to-teal-600",
    description: "Subject receives the action",
    descriptionTH: "ประธานเป็นผู้รับกระทำ",
  },
  {
    id: "articles",
    name: "Articles",
    nameTH: "Article",
    icon: "📌",
    subtopics: 3,
    importance: "high",
    color: "from-yellow-500 to-orange-600",
    description: "a, an, the — rules and usage",
    descriptionTH: "กฎการใช้ a, an, the",
  },
  {
    id: "prepositions",
    name: "Prepositions",
    nameTH: "Preposition",
    icon: "🔗",
    subtopics: 8,
    importance: "medium",
    color: "from-red-500 to-rose-600",
    description: "In, on, at, by, for, with and more",
    descriptionTH: "In, on, at, by, for, with และอื่นๆ",
  },
  {
    id: "connectors",
    name: "Connectors",
    nameTH: "คำเชื่อม",
    icon: "🧲",
    subtopics: 6,
    importance: "very high",
    color: "from-cyan-500 to-blue-600",
    description: "Conjunctions, transitional phrases",
    descriptionTH: "Conjunctions และ transitional phrases",
  },
];

export const mockTestQuestions = [
  {
    id: 1,
    part: 5,
    question: "The marketing team _____ the new campaign last week.",
    options: ["launch", "launched", "launching", "will launch"],
    correct: 1,
    explanation:
      "'last week' indicates past tense, so 'launched' is correct.",
    explanationTH: "'last week' บอกว่าเป็นอดีต ดังนั้น 'launched' ถูกต้อง",
    category: "tenses",
  },
  {
    id: 2,
    part: 5,
    question: "All employees are required _____ the safety training.",
    options: ["complete", "completing", "to complete", "completed"],
    correct: 2,
    explanation: "After 'required', use 'to + infinitive'.",
    explanationTH: "หลัง 'required' ใช้ 'to + infinitive'",
    category: "grammar",
  },
  {
    id: 3,
    part: 5,
    question: "The report _____ submitted before the deadline.",
    options: [
      "must be",
      "must have",
      "should have been",
      "would have",
    ],
    correct: 0,
    explanation: "Passive voice with modal: 'must be + past participle'.",
    explanationTH: "Passive voice กับ modal: 'must be + past participle'",
    category: "passive",
  },
  {
    id: 4,
    part: 5,
    question: "_____ the heavy rain, the outdoor event was cancelled.",
    options: ["Despite", "Because", "Due to", "Although"],
    correct: 2,
    explanation: "'Due to' is followed by a noun phrase (heavy rain).",
    explanationTH: "'Due to' ตามด้วย noun phrase",
    category: "connectors",
  },
  {
    id: 5,
    part: 5,
    question: "The manager asked the team to work _____ on the project.",
    options: ["collaborative", "collaboration", "collaboratively", "collaborate"],
    correct: 2,
    explanation: "An adverb is needed to modify the verb 'work'.",
    explanationTH: "ต้องใช้ adverb เพื่อขยาย verb 'work'",
    category: "parts-of-speech",
  },
];

export const suggestedAIQuestions = {
  th: [
    "อธิบาย Passive Voice ให้เข้าใจง่ายๆ",
    "สร้าง Flashcard 10 คำศัพท์ธุรกิจ",
    "Part 5 ต้องเน้นเรื่องอะไรบ้าง?",
    "สร้างข้อสอบ Part 5 ให้ 5 ข้อ",
    "วิเคราะห์จุดอ่อนของฉันจากผลทดสอบ",
    "แผนการเรียน TOEIC 3 เดือนจนถึง 800",
    "คำศัพท์ TOEIC ที่ออกบ่อยที่สุด 20 คำ",
    "เทคนิคทำ Part 7 ให้ได้คะแนนสูง",
  ],
  en: [
    "Explain Passive Voice in simple terms",
    "Create 10 business vocabulary flashcards",
    "What should I focus on for Part 5?",
    "Generate 5 Part 5 practice questions",
    "Analyze my weak areas from test results",
    "Create a 3-month study plan for score 800",
    "Top 20 most common TOEIC vocabulary",
    "Tips to maximize score on Part 7",
  ],
};
